version: '3.9'

services:
  med-friend-db-sql:
    image: postgres:16.2
    container_name: ${CONTAINER_NAME}
    ports:
      - 7500:5432
    volumes:
      - ./med-friend-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
