version: '3.9'

services:
  med-friend-db-sql:
    image: postgres:16.2
    container_name: ${CONTAINER_NAME}
    ports:
      - 7500:5432
    volumes:
      - ./med-friend-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - consul-network
    labels:
      - "consul.register=true"
      - "consul.service.name=med-friend-db-sql"
      - "consul.service.port=5432"
      - "consul.check.interval=10s"
      - "consul.check.timeout=5s"
      - "consul.check.script=docker exec ${CONTAINER_NAME} pg_isready -U ${POSTGRES_USER}"

  consul:
    image: consul:1.15.4
    container_name: consul-medfri
    ports:
      - "8500:8500"  # Consul UI
      - "8600:8600"  # Consul DNS
      - "8600:8600/udp"  # Consul DNS UDP
    command: "agent -server -bootstrap -ui -client=0.0.0.0"
    volumes:
      - ./consul-data:/consul/data
    environment:
      CONSUL_BIND_INTERFACE: eth0
    networks:
      - consul-network

networks:
  consul-network:
    driver: bridge
