version: '3.9'

services:
  med-friend-db-sql:
    image: postgres:16.2
    container_name: ${CONTAINER_NAME}
    ports:
      - 7500:5432
    volumes:
      - ./med-friend-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  consul:
    image: consul:1.15.4
    container_name: consul-medfri
    ports:
      - "8500:8500"  # Consul UI
      - "8600:8600"  # Consul DNS
    command: "agent -dev -client 0.0.0.0" 
    volumes:
      - ./consul-data:/consul/data
    environment:
      CONSUL_BIND_INTERFACE: eth0

  redis:
    image: redis:7.0
    container_name: redis-medfriend
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis-data:/data